@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YzY0ZDUzYS02NjkwLTRkMjgtOTY0Zi1kZDQyMTJkMDJhOGUiLCJlbWFpbCI6InRvYmlhc2JhcmFrYWhAZ21haWwuY29tIiwicm9sZSI6ImRyaXZlciIsImlhdCI6MTc3Njg1NTc1NiwiZXhwIjoxNzc3NDYwNTU2fQ.hTiqXu8A-kZXcI0_NAsnkpH-6Xqvgwk8Q_73FajmsqY


### Create complete driver profile
POST http://localhost:3000/api/v1/driver/profile
Content-Type: application/json
Cookie: access_token={{access_token}}

{
  "licenseNumber": "DL123456789",
  "status": "online",
  "currentLatitude": -1.286389,
  "currentLongitude": 36.817223,
  "vehicle": {
    "plateNumber": "KCA123A",
    "model": "Probox",
    "type": "pickup",
    "year": 2020,
    "capacityKg": 500
  }
}