# @access_token = {{login.response.headers.set-cookie.[0].split(';')[0].split('=')[1]}}
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ODRjYzhjOC1iN2YyLTRhYmQtYTMyMy1iNzgyYTJiMjhiZTAiLCJlbWFpbCI6InRvYmlhc2JhcmFrYWhAZ21haWwuY29tIiwicm9sZSI6ImRyaXZlciIsImlhdCI6MTc3NjUxMzMyMywiZXhwIjoxNzc3MTE4MTIzfQ.xtHpexGUiuc8M8q3s5t04HBXOC_m0kGScgIXlynT2fA; access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZDJkMTUwZS0zZWY0LTQyYzctOWE2Ni0xNTQ4ZTE3YTgxZDEiLCJlbWFpbCI6ImNsaWVudDFAZXhhbXBsZS5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzc2NTEzNDMwLCJleHAiOjE3NzcxMTgyMzB9.sOO1GrKfJEJ5g2cagJ7PPkwjJ7MJgp5x5iZ5SoFO3gU


GET http://localhost:3000/api/v1/admin/drivers
Cookie: access_token={{access_token}}

