### Client creates order
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYzQ4MzY5Yy00ODkyLTRlOTAtYTg4My1jZjg3ODNjZDNjN2UiLCJlbWFpbCI6InRvYmlhc2JhcmFrYW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc2ODU1ODc1LCJleHAiOjE3Nzc0NjA2NzV9.PwyaCgGwS65m6teE88sn5Qq32lCNGzL-CSiGiZ0HooQ

POST http://localhost:3000/api/v1/orders
Content-Type: application/json
Cookie: access_token={{access_token}}

{
  "customerName": "John Client",
  "customerPhone": "+254700000000",
  "customerEmail": "client@example.com",

  "deliveryAddress": "Nairobi CBD, Kencom Bus Station",
  "deliveryLandmark": "Near Hilton",

  "deliveryLat": -1.286389,
  "deliveryLng": 36.817223,

  "requiresPickup": false,

  "timeWindowStart": "10:00",
"timeWindowEnd": "14:00",

  "priority": "NORMAL",
  "deliveryInstructions": "Call on arrival",
  "isFragile": false,
  "requiresSignature": true,
  "requiresPhoto": true,

  "subtotal": 1500,
  "deliveryFee": 300,
  "totalAmount": 1800,

  "paymentMethod": "CARD",

  "items": [
    {
      "itemName": "Laptop",
      "quantity": 1,
      "unitPrice": 1500,
      "weightKg": 2,
      "sku": "LAP-001",
      "notes": "Handle with care"
    }
  ],

  "images": [
    {
      "imageUrl": "https://example.com/item.jpg",
      "imageType": "SIGNATURE",
      "caption": "Laptop box"
    }
  ]
}

